In [1]:
import numpy as np
import pandas as pd

In [2]:
#samples
n = 10
#variants
m = 5
#frequency of 1
f_i = 3./4
#whatever is left is frequency for zero
f_zero = 1-f_i

#here every matrix entree has to be zero or one, with having a f_i probability to get selected
G = np.random.choice([0, 1], size=(n,m), p=[f_zero, f_i])
#Random Array of Zeros and Ones, no frequency
#G = np.random.choice([0, 1], size=(n,m))
print(G)

[[1 0 1 0 1]
 [1 1 1 0 0]
 [1 1 1 0 1]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [0 0 0 1 0]
 [0 1 0 1 0]
 [1 1 1 1 0]
 [1 0 1 1 1]
 [1 1 0 1 1]]


In [17]:
from math import sqrt
import random

# mean and standard deviation
Y=[]
H=0
def Make_PhenoType(G,var_e,var_g):
    rows = len(G)
    columns = len(G[0])
    mean = 0 
    #because we are given variance and python random.normal only accepts std, we need to convert variance to std
    sigma_e = sqrt(var_e)
    sigma_b = sqrt(var_g)
    b_i = np.random.normal(0, sigma_b)
    Y =[]
    for k in range(0, rows+1):
        #samples =1000
        e_j = np.random.normal(0, sigma_e)
        i = random.randint(0,rows-1)
        j = random.randint(0,columns-1)
        #Assuming G_ij = SNP, pick a random G entree
        G_ij  = G[i,j]
        Y_j = b_i*G_ij + e_j
        Y.append(Y_j)
    H= var_g/(var_g+var_e)
    return Y,H

#Version with no loop, this assumes that y_j is a singular value and not a collection of values
# as in the previous function
def Make_PhenoType_Singular(G,var_e,var_g):
    rows = len(G)
    columns = len(G[0])
    mean = 0 
    sigma_e = sqrt(var_e)
    sigma_b = sqrt(var_g)
    b_i = np.random.normal(0, sigma_b)
     #samples =1000
    e_j = np.random.normal(0, sigma_e)
    i = random.randint(0,rows-1)
    j = random.randint(0,columns-1)
    #Assuming G_ij = SNP, pick a random G entree
    G_ij  = G[i,j]
    Y_j = b_i*G_ij + e_j
    H= var_g/(var_g+var_e)
    #returning i so we know which individual the phenotype is for
    return Y_j,H,i
    

In [22]:
Y,H,sample= Make_PhenoType_Singular(G,.1,.1)

In [23]:
print('Phenotype for individual '+str(sample)+" is " +str(Y))

Phenotype for individual 7 is 0.010493688035843357
