In [1]:
import numpy as np
import pandas as pd

In [2]:
#samples
n = 10
#variants
m = 5
#frequency of 1
f_i = 3./4
#whatever is left is frequency for zero
f_zero = 1-f_i

G = np.random.choice([0, 1], size=(n,m), p=[f_zero, f_i])
#Random Array of Zeros and Ones, no frequency
#G = np.random.choice([0, 1], size=(n,m))
print(G)

[[1 1 1 1 1]
 [1 1 1 1 0]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 0 1 0]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [1 1 1 1 0]
 [1 0 1 1 1]
 [1 1 1 0 1]]


In [23]:
from math import sqrt
import random

# mean and standard deviation
Y=[]
H=0
def Make_PhenoType(G,var_e,var_g):
    rows = len(G)
    columns = len(G[0])
    mean = 0 
    sigma_e = sqrt(var_e)
    sigma_b = sqrt(var_g)
    b_i = np.random.normal(0, sigma_b)
    Y =[]
    for k in range(0, columns+1):
        #samples =1000
        e_j = np.random.normal(0, sigma_e)
        i = random.randint(0,rows-1)
        j = random.randint(0,columns-1)
        #Assuming G_ij = SNP, pick a random G entree
        G_ij  = G[i,j]
        Y_j = b_i*G_ij + e_j
        Y.append(Y_j)
        H= var_g/(var_g+var_e)

    return Y,H
    

In [24]:
Y,H= Make_PhenoType(G,.1,.1)

In [25]:
Y

[0.356504562809019,
 0.024478014390938524,
 -0.21139099033010095,
 -0.2967073596138386,
 0.2912347293339032,
 -0.2909822808132354]