In [1]:
import numpy as np
import pandas as pd

In [2]:
#variants
n = 10
#people
m = 5
#frequency of 1
f_i = 3./4
#whatever is left is frequency for zero
f_zero = 1-f_i

#here every matrix entree has to be zero or one, with having a f_i probability to get selected

G = np.random.choice([0, 1], size=(n,m), p=[f_zero, f_i])
#Random Array of Zeros and Ones, no frequency
#G = np.random.choice([0, 1], size=(n,m))
print(G)

[[1 1 1 1 0]
 [1 0 1 1 0]
 [0 0 0 1 1]
 [1 1 1 1 0]
 [0 0 1 1 1]
 [1 1 0 1 0]
 [0 1 1 0 1]
 [1 1 0 1 1]
 [1 1 0 1 0]
 [1 0 0 1 0]]


In [9]:
from math import sqrt
import random

# mean and standard deviation
Y=[]
H=0
# def Simulate_PhenoType(G,var_e,var_g):
#     rows = len(G)
#     columns = len(G[0])
#     mean = 0 
#     #because we are given variance and python random.normal only accepts std, we need to convert variance to std
#     sigma_e = sqrt(var_e)
#     sigma_b = sqrt(var_g)
#     b_i = np.random.normal(0, sigma_b)
#     Y =[]
#     for k in range(0, columns):
#         #samples =1000
#         e_j = np.random.normal(0, sigma_e)
#         i = random.randint(0,rows-1)
#         j = random.randint(0,columns-1)
#         #Assuming G_ij = SNP, pick a random G entree
#         G_ij  = G[i,j]
#         Y_j = b_i*G_ij + e_j
#         Y.append(Y_j)
#     H= var_g/(var_g+var_e)
#     return Y,H

#Version with no loop, this assumes that y_j is a singular value and not a collection of values
# as in the previous function
def Simulate_PhenoType_Singular(G,var_e,var_g):
    rows = len(G)
    columns = len(G[0])
    mean = 0 
    sigma_e = sqrt(var_e)
    sigma_b = sqrt(var_g)
    b_i = np.random.normal(0, sigma_b)
     #samples =1000
    e_j = np.random.normal(0, sigma_e)
    i = random.randint(0,rows-1)
    j = random.randint(0,columns-1)
    #Assuming G_ij = SNP, pick a random G entree
    G_ij  = G[i,j]
    Y_j = b_i*G_ij + e_j
    H= var_g/(var_g+var_e)
    #returning i so we know which individual the phenotype is for
    return Y_j,H,i
    
#third interpretation, this assumes that we are making a Y_j for every individual and 
#in each loop we choose a random variant for that person
def Simulate_PhenoType_PerPerson(G,var_e,var_g):
    #rows are the loci so each person has a row of different loci
    rows = len(G)
    #where columns are the individuals
    columns = len(G[0])
    mean = 0 
    #because we are given variance and python random.normal only accepts std, we need to convert variance to std
    sigma_e = sqrt(var_e)
    sigma_b = sqrt(var_g)
    b_i = np.random.normal(0, sigma_b)
    Y =[]
    for k in range(0, columns):
        #samples =1000
        #each person will have a random e_j value
        e_j = np.random.normal(0, sigma_e)
        #pick a random variant for individual k
        i = random.randint(0,rows-1)
        #Assuming G_ij = SNP, pick a random SNP for each individual
        G_ij  = G[i,k]
        Y_j = b_i*G_ij + e_j
        Y.append(Y_j)
    H= var_g/(var_g+var_e)
    return Y,H
    

In [10]:
Y,H = Make_PhenoType_PerPerson(G,.1,.1)

In [11]:
#third function assumes that for each person j in M we make a phenotype for them
print('Phenotypes for total individuals: '+str(len(G[0]))+" is " +str(Y))

Phenotypes for total individuals: 5 is [-0.4023087085100261, -0.06580090336891144, -0.00647565995343552, 0.3338945725166361, -0.43093949548133503]
