In [1]:
import numpy as np
import pandas as pd

In [2]:
#samples
n = 10
#variants
m = 10
#frequency of 1
f_i = 3./4
#whatever is left is frequency for zero
f_zero = 1-f_i
G = np.random.choice([0, 1], size=(n,m), p=[f_zero, f_i])
#Random Array of Zeros and Ones, no frequency
#G = np.random.choice([0, 1], size=(n,m))
print(G)

[[0 1 1 1 1 0 0 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 1 1 1 0 1 1]
 [1 0 1 1 1 1 0 0 1 1]
 [1 0 1 1 0 1 0 1 1 1]
 [1 1 1 1 0 1 1 1 1 1]
 [1 0 0 1 1 0 1 0 1 1]
 [0 1 1 0 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 1 0 0]
 [1 0 0 0 1 1 0 1 1 1]]


In [7]:
#row
i = 0
#column
j = 0
G_ij  = G[i,j]
# SNP = 
# b_i  = np.random.normal(0, var_g)
# Y_j = b_i*G_ij + e_j
